on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: airvzxf/ftp-deployment-action@latest
      with:
        server: ftpupload.net
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_dir: "./"
        remote_dir: "/ai-jobanalytic.infinityfreeapp.com/htdocs/"
        max_retries: "10"
        timeout: "86400000"
        lftp_settings: "set ftp:passive-mode off; set net:timeout 60s; set net:max-retries 3; set net:reconnect-interval-base 5;"
        log-level: "verbose"
