name: Deploy to InfinityFree

# Run manually or on push to the main branch
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the latest code from GitHub
      - name: Get latest code
        uses: actions/checkout@v4

      # Step 2: Upload code via FTP
      - name: Deploy to InfinityFree via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ftpupload.net
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./"
          remote_dir: "/ai-jobanalytic.infinityfreeapp.com/htdocs/"
          max_retries: "20"
          delete: "false"
          ftp_ssl_allow: "false"
          ftp_use_feat: "false"
          ftp_nop_interval: "30"
          net_max_retries: "10"
          net_persist_retries: "10"
          net_timeout: "120s"
          dns_max_retries: "10"
          dns_fatal_timeout: "30"
